struct FBANEvents {
    static let bannerClick = "fban.banner.click"
    static let bannerClose = "fban.banner.close"
    static let bannerExitApp = "fban.banner.exit_app"
    static let bannerImpression = "fban.banner.impression"
    static let bannerLoad = "fban.banner.load"
    static let bannerLoadFail = "fban.banner.load_fail"
    static let bannerOpen = "fban.banner.open"
    static let interstitialClick = "fban.interstitial.click"
    static let interstitialClose = "fban.interstitial.close"
    static let interstitialExitApp = "fban.interstitial.exit_app"
    static let interstitialImpression = "fban.interstitial.impression"
    static let interstitialLoad = "fban.interstitial.load"
    static let interstitialLoadFail = "fban.interstitial.load_fail"
    static let interstitialOpen = "fban.interstitial.open"
    static let ready = "fban.ready"
    static let rewardVideoClick = "fban.reward_video.click"
    static let rewardVideoClose = "fban.reward_video.close"
    static let rewardVideoComplete = "fban.reward_video.complete"
    static let rewardVideoExitApp = "fban.reward_video.exit_app"
    static let rewardVideoImpression = "fban.reward_video.impression"
    static let rewardVideoLoad = "fban.reward_video.load"
    static let rewardVideoLoadFail = "fban.reward_video.load_fail"
    static let rewardVideoOpen = "fban.reward_video.open"
    static let rewardVideoReward = "fban.reward_video.reward"
    static let rewardVideoStart = "fban.reward_video.start"
}
