struct FBANEvents {
    static let bannerClick = "fban.banner.click"
    static let bannerImpression = "fban.banner.impression"
    static let bannerLoadFail = "fban.banner.load_fail"
    static let interstitialClick = "fban.interstitial.click"
    static let interstitialClose = "fban.interstitial.close"
    static let interstitialImpression = "fban.interstitial.impression"
    static let interstitialLoad = "fban.interstitial.load"
    static let interstitialLoadFail = "fban.interstitial.load_fail"
    static let interstitialWillClose = "fban.interstitial.will_close"
    static let ready = "fban.ready"
    static let rewardVideoClick = "fban.reward_video.click"
    static let rewardVideoClose = "fban.reward_video.close"
    static let rewardVideoComplete = "fban.reward_video.complete"
    static let rewardVideoExitApp = "fban.reward_video.exit_app"
    static let rewardVideoImpression = "fban.reward_video.impression"
    static let rewardVideoLoad = "fban.reward_video.load"
    static let rewardVideoLoadFail = "fban.reward_video.load_fail"
    static let rewardVideoServerSuccess = "fban.reward_video.server_success"
    static let rewardVideoServerFail = "fban.reward_video.server_fail"
    static let rewardVideoWillClose = "fban.reward_video.will_close"
}
